[package]
name = "grad-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
env_logger = "0.11.7"
log = "0.4.26"
plotters = "0.3.7"
rand = "0.9.0"
rand_distr = "0.5.1"
rand_pcg = "0.9.0"
thiserror = "2.0.12"
